### ISSUE TITLE
Please add community guidelines

### ISSUE THREAD

**Issue by diyadas** [arsilva87/biotools#5]
As per openjournals/joss-reviews#1321

I was not able to find community guidelines. As per the reviewing rubric:
>Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

The `usethis` package has a function `use_tidy_contributing` that can guide you through this.

**Comment by arsilva87** [comment]
@diyadas Done.
